export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    verifyEmail: '/auth/verify-email',
    resendVerificationCode: '/auth/resend-verification-code',
  },
  me: {
    show: '/me',
    update: '/me',
    updateAvatar: '/me/avatar',
    requestPasswordChangeCode: '/me/request-password-change-code',
    changePassword: '/me/change-password',
    setupPinCode: '/me/pin-code',
    changePinCode: '/me/pin-code',
    getWorkSchedule: '/me/work-schedule',
  },
  users: {
    index: '/users',
    show: (id: number | string) => `/users/${id}`,
  },
  messages: {
    index: (receiverId: number | string) => `/messages/${receiverId}`,
    store: '/messages',
  },
  companies: {
    showById: (id: number) => `/companies/${id}`,
    showByName: (name: string) => `/companies/name/${name}`,
  },
  leaveRequests: {
    index: '/leave-requests',
    store: '/leave-requests',
    show: (id: number | string) => `/leave-requests/${id}`,
  },
  manager: {
    company: {
      statistics: '/managers/company/statistics',
      exportStatistics: '/managers/company/statistics/export',
    },
    users: {
      index: '/managers/users',
      show: (userId: number | string) => `/managers/users/${userId}`,
      timeEntries: (userId: number | string) => `/managers/users/${userId}/time-entries`,
      timeSummary: (userId: number | string) => `/managers/users/${userId}/time-summary`,
      exportStatistics: (userId: number | string) => `/managers/users/${userId}/statistics/export`,
      workSchedule: (userId: number | string) => `/managers/users/${userId}/work-schedule`,
      updateWorkSchedule: (userId: number | string) => `/managers/users/${userId}/work-schedule`,
    },
    leaveRequests: {
      index: '/managers/leave-requests',
      pending: '/managers/leave-requests/pending',
      approve: (leaveRequestId: number) => `/managers/leave-requests/${leaveRequestId}/approve`,
      reject: (leaveRequestId: number) => `/managers/leave-requests/${leaveRequestId}/reject`,
    },
  },
  workSchedules: {
    index: '/work-schedules',
    store: '/work-schedules',
    show: (id: number | string) => `/work-schedules/${id}`,
    update: (id: number | string) => `/work-schedules/${id}`,
    delete: (id: number | string) => `/work-schedules/${id}`,
  },
  timeEntries: {
    index: '/time-entries',
    store: '/time-entries',
    show: (id: number | string) => `/time-entries/${id}`,
    delete: (id: number | string) => `/time-entries/${id}`,
    active: '/time-entries/active',
    stopActive: '/time-entries/active/stop',
    summaryByCurrentUser: '/time-entries/summary/me',
    export: '/time-entries/export',
  },
  qrCode: {
    daily: '/qr-code/daily',
  },
  admin: {
    companies: {
      store: '/admin/companies',
      update: (id: number | string) => `/admin/companies/${id}`,
      updateLogo: (id: number | string) => `/admin/companies/${id}/logo`,
      delete: (id: number | string) => `/admin/companies/${id}`,
      assignManager: (id: number | string) => `/admin/companies/${id}/assign-manager`,
      addEmployee: (id: number | string) => `/admin/companies/${id}/add-employee`,
      removeEmployee: (id: number | string) => `/admin/companies/${id}/remove-employee`,
      getUsersByCompany: (id: number | string) => `/admin/companies/${id}/users`,
    },
    users: {
      index: '/admin/users',
      show: (id: number | string) => `/admin/users/${id}`,
      update: (id: number | string) => `/admin/users/${id}`,
      updateRole: (id: number | string) => `/admin/users/${id}/role`,
      updateWorkMode: (id: number | string) => `/admin/users/${id}/work-mode`,
      resetPassword: (id: number | string) => `/admin/users/${id}/reset-password`,
      delete: (id: number | string) => `/admin/users/${id}`,
    },
  },
  auditLogs: {
    index: '/audit-logs',
    all: '/audit-logs/all',
  },
  app: {
    updateCheck: '/app/update-check',
  },
} as const
